### ISSUE TITLE
ADAP : chek Controle existant

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#102]
Pour regarder des contrôles déjà saisis : quelque soit le contrôle, une fois que l'on arrive à l'onglet "navires observés" et que l'on clique sur un navire, on est automatiquement redirigé vers la page d'accueil.

**Comment by hgaden** [comment]
Vrai sous Chrome et Firefox

**Comment by blavenie** [comment]
C'est normal, l'écran de détail n'est pas encore déployé.
