### ISSUE TITLE
ADAP : pas possible d'ajouter une nouvelle marée en tant que superviseur

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#103]
L'ajout de nouvelles marées n'est possible qu'en mode Observateur.

**Comment by blavenie** [comment]
Le problème vient du fait que l'utilisateur était "inactif", dans la BDD de test.
Je le corrige pour les prochaines livraisons, en ajoutant un autre utilisateur pour tester le cas d'inactivité.
