### ISSUE TITLE
ADAP / Marée / lieu : défilement 

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#104]
V11. 1 : La liste des lieux apparaît à la saisie, mais on n'a pas la possibilité de la faire défiler. (valable pour port départ, port arrivée, lieu de vente)

**Comment by hgaden** [comment]
Au passage, attention à la blague qui pourrait rester, volontaire ou non ;) : "FRBOL - Boulogne-sur-**merde**"

**Comment by hgaden** [comment]
BUG valable que sur telephone android, pas sur PC

**Comment by blavenie** [comment]
Cela semble fonctionner sur les tablette Android ciblé par LPDB (Samsung active pro)
