### ISSUE TITLE
SUMARiS / Marée / main observed Métier / forcer majuscule

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#106]
V11. 1 : forcer la saisie en majuscule pour écrire les métiers.

**Comment by hgaden** [comment]
BUG valable que sur telephone android et sur PC

**Comment by blavenie** [comment]
@hgaden es-tu sur que ce n'est pas plutot pour le programme SUMARiS ?
Car il n'y a pas de "main observed métier" dans les programmes de collecte ADAP-*
Peux tu changer le titre, du coup ?

**Comment by blavenie** [comment]
Ne sera pas corrigé : le mieux serait à terme d'utiliser un référentiel métier nationaux, plutot qu'un champs libre. A faire dans les prochaines années.
