### ISSUE TITLE
ADAP / Marée / operation de pêche : non accessible

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#108]
v0.11. 1 : le formulaire operation de pêche est visible, mais il n'est pas accessible à la saisie.

**Comment by hgaden** [comment]
BUG valable que sur telephone android, pas sur PC

**Comment by blavenie** [comment]
Peux tu m'en dire plus sur la marée utilisée ? et le compte utilisateur.
Afin que je reproduise.
Merci !

**Comment by hgaden** [comment]
je me suis connecté en tant que demo@sumaris.net.
ça concerne la marée du 05/05/2019 12:00 au 05/05/2019 a 16:00 VIA ANDROID

**Comment by hgaden** [comment]
Pour info, toujours sur android/téléphone portable : à vérifier, mais le format des dates est MM/JJ/AAAA au lieu de JJ/MM/AAAA dans le tableau listing des marées. A modifier pour une meilleure lisibilité.

**Comment by blavenie** [comment]
Peux tu ouvrir un autre ticket pour les formats de dates, stp ?
