### ISSUE TITLE
ADAP / Marée / OP et capture : surlignage rouge erreur absent

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#111]
Les champs en erreur ne sont pas toujours surlignés en rouge quand erreur (exemple, si on oublie de remplir le métier ou l'engin, ça ne surligne pas forcément en rouge pour indiquer l'erreur ou le manque d'information. Du moins, tant qu'on ne met pas le curseur sur le champ.

**Comment by hgaden** [comment]
Tester sur PC uniquement car pas d’accès via le téléphone portable

**Comment by blavenie** [comment]
Corrigé en v0.14.4
