### ISSUE TITLE
ADAP /Marée / Opération de pêche / Référentiel métier à revoir

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#112]
Pour certains métiers, revoir l'écriture. Notamment : OTBMNZ OTBNEP en OTB-MNZ et OTB-NEP

**Comment by hgaden** [comment]
Tester sur PC uniquement car pas d’accès via le téléphone portable

**Comment by blavenie** [comment]
En fait, ces codes reprennent les "métier nationaux" du SIH.
Notamment, si oin ajoute un "-" au milieu, comment distinguer les code espèce qui ne sont pas encore dans la classification FAO.

Par exemple : 
 * "_GA" pour les gadidés. Le code métier est OTB_GA car le code espèces est "8GA".
N'est-ce pas gênant si on change en "OTB-_GA" ? Ca fait bizarre, non ?

Par ailleurs, pour synchroniser avec la BDD Harmonie, il faudra bien exactement les même code.

Qu'en penses tu @hgaden  ?

**Comment by hgaden** [comment]
L'essentiel pour moi est en effet de coller à la BDD Harmonie qui doit normalement coller avec les référentiels FAO. Les Gadiformes ont le code FAO "GAD". POur moi, tous les codes FAO sont à 3 caractères... mais peut-être pas dans Harmonie, à vérifier... 
Pour info, voilà une liste des codes FAO des espèces
[liste_especes_-_code_fao.pdf](https://github.com/sumaris-net/sumaris-app/files/3176376/liste_especes_-_code_fao.pdf)
On en reparle à mon retour si tu veux.

**Comment by blavenie** [comment]
Dans Harmonie, les code espèce non référencé par la FAO, sont préfixé d'un "_". Ensuite, il font une demande à la FAO, qui peut mettre un certain temps avant de l'inétgrer.
Ensuite Harmonie doit intégrer le nouveau code.  C'est sans doute cette dernière étape qui manque...

**Comment by blavenie** [comment]
La saisie se fait maintenant par l'espèce cible. Les code métier ne sont donc plus visible. Je ferme ce ticket
