### ISSUE TITLE
Referential administration > Maximize size of the "code" column

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#119]
En voulant que les colonnes s'élargissent pour voir l'ensemble d'une information dedans, j'ai décoché la visualisation de certaines colonnes. Il n'en reste qu'une, mais elle ne s’élargit pas / ne se met pas à l'échelle de la taille dispo à l'écran. Ce point mériterait d'être amélioré (utile pour les champs à grande valeur).
![image](https://user-images.githubusercontent.com/45093466/59849090-0a959300-9367-11e9-8824-99aee3dffe07.png)

**Comment by hgaden** [comment]
Le problème n'a l'air d'être vrai que pour le champ "Code" ; j'ai essayé avec les autres et ils s'allongent : 
![image](https://user-images.githubusercontent.com/45093466/59849589-4f6df980-9368-11e9-86b3-1bf7539a7e57.png)

**Comment by blavenie** [comment]
Oui, j'ai du mettre un taille max par défaut pour le code
