### ISSUE TITLE
ADAP-SUMARiS / changement d'icone pour meilleure visibilité

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#120]
L’icône  loupe pour recherché va, mais c'est le même icône qui est utilisé pour la notion de filtre.
Proposition : modifier l'îcone et utiliser un îcone similaire à cette image : 
![image](https://user-images.githubusercontent.com/45093466/59850679-200cbc00-936b-11e9-9856-a0c500993c58.png)

**Comment by blavenie** [comment]
C'est fait en v0.16.0 j'utilise une icone proche de celle que tu propose
