### ISSUE TITLE
Rafraîchissement automatique des OP

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#130]
LPDB : Lors de la saisie d’une nouvelle opération j’ai été obligé d’appuyer sur le bouton rafraîchir pour la voir apparaître. Ne serait ce pas possible qu’une nouvelle opération apparaisse dès qu’elle a été enregistrée ?

Hélène : ce n'est pas bloquant, mais ça améliorerait en visibilité

**Comment by blavenie** [comment]
fait
