### ISSUE TITLE
tests v0.17.1 (LPDB) Capture / Élargir choix noms Espèces

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#131]
LPDB : Lors de la saisie d’un nouveau Lot Espèce; nous n’avons accès que à baudroie / Eglefin. Il faudrait pouvoir l’ouvrir à minima sur d’autres espèces comme le COD-CABILLAUD et à court terme le pocheteau.

Hélène : Selon moi, il s'agit d'autres projet après. Il y a le projet Pocheteau qui ne sera ouvert qu'aux espèces de Pocheteau et le projet cabillaud.
LPDB travaille sur tous ces projets ; du coup, faut-il laisser l'entrée par projet en considérant que d'autres organismes peuvent accéder à un seul projet et non tous, ou part-on du principe que si c'est de l'auto-échantillonnage, on laisse la porte ouverte à un listing d'espèces qui évoluera en fonction du temps. A noter que les points de collecte peuvent aussi évoluer en fonction des espèces et donc des programmes.
Personnellement, je pense plus facile à gérer en gardant l'entrée par programme. A voir de votre côté ?

**Comment by blavenie** [comment]
Doublon avec le ticket #149
