### ISSUE TITLE
 Catch screen / mode terrain / Garde fou sur LAN/DIS

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#134]
Si on se fie au formulaire papier d'ADAP, on ne saisie en 1er lieu que des poids LAN, DIS par espèce pour une OP donnée, puis on saisie le poids de la fraction mesurée par espèce en DIS et LAN.

- [ ] Faire en sorte que si seulement LAN indiqué dans le tableau des captures, alors qu'il ne soit pas possible de taper des DIS dans le tableau des mesures.

**Comment by blavenie** [comment]
C'est plus compliqué, car à priori les mesures sont saisies avant les poids LAN/DIS.
Ne sera donc pas corrigé (pour ADAP en tous cas)
