### ISSUE TITLE
Test v0.17.3 Catch / double entrer espèce commerciale espèce scientifique

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#135]
Tel qu'est fait l'outil actuellement, seul le poids pour la baudroie MNZ est spécifié dans l'onglet capture. C'est dans l'onglet mesures que l'on différencie après par mensuration les espèces ANK ou MON (noir et blanche). Dans les fiches terrain remplies que vous nous avez fournies, la fiche "mesure baudroie" indique le poids totale de l'espèce commercial et le poids de la fraction mesurée, en spécifiant au stylo s'il s'agite de la blanche ou la noire (on n'est donc plus ici sur l'espèce commerciale, mais bien l'espèce scientifique). Avez vous besoin des poids de baudroies par espèces scientifique (MON et ANK) ? Si oui, Dans le tableau capture, l'entrée n'est plus que l'espèce commerciale, mais l'espèce commerciale et l'espèce scientifique : 
- MNZ-MNZ : ce cas pose problème car autorise de ne pas rentrer l'information par espèces scientifique ANK ou MON...
- MNZ-ANK
- MNZ-MON
![image](https://user-images.githubusercontent.com/45093466/66319817-06917f00-e91e-11e9-99c4-d11fab4f7994.png)

**Comment by blavenie** [comment]
Vu avec Thomas : on laisse comme avant (uniquement le poids sur l'espèce commerciale)
