### ISSUE TITLE
Operation / Add PSFM "Sampling ? (O/N)" 

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#136]
Test : 0.17.3

Certaines OP sont échantillonnées, d'autre non pour une même marée. Avec Benoît, on se demande s'il ne manque pas une information dans l'écran détail de l'opération, où serait indiqué l'information échantillonnage "OUI"/"NON" ou où serait spécifié un échantillonnage "capture avec mensuration"/"capture avec poids uniquement". L'avantage de procéder ainsi est de laisser accès ou non à l'onglet mesures individuelles. Ceci peut fonctionner à moins que tu nous dises que certaines fois on peut mettre une mesure =individuelle et d'autre fois on, au cours de la même opération de pêche. Est ce que la mensuration est liée à l'OP comme c'est suggéré dans votre formulaire ? ou est ce que vous pourriez vouloir ne saisir que le poids total de l'églefin et après faire les mesures sur la baudroie par exemple ?

**Comment by blavenie** [comment]
Pas utile, pour ADAP, depuis l'arriver du PSFM "Type d'échantillonnage"
