### ISSUE TITLE
Trip / coordonnées géographiques / Forcer OUEST

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#137]
Dans Sumaris, les pêches avaient surtout lieu à l'Est du Méridien de Greenwic, ; dans ADAP, elles ont surtout lieu à l'ouest. --> Forcer OUEST pour éviter les erreurs de saisie. Quand pas saisie, d'office est pour le moment 

![image](https://user-images.githubusercontent.com/45093466/66320561-54f34d80-e91f-11e9-8e45-507363f86c5e.png)

Suggestion : peut-être prévoir dans les paramètres d'utilisateur, la possibilité de choir Nord/Sud et Est/Ouest selon chacun, sans que ce soit forcer, mais d'office si pas saisi.

**Comment by blavenie** [comment]
Corrigé en 1.2.2. La direction par défaut (par exemple N / W ) peut-être configurée au niveau du programme de collecte, via une propriété de configuration
