### ISSUE TITLE
tests v0.17.3 - ADAP / Individual measure / Mode bureau / Mode sans rafale ne fonctionne pas

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#138]
impossible de sauvegarder pour ajouter la ligne de mensuration en mode normal
![image](https://user-images.githubusercontent.com/45093466/66322146-f4194480-e921-11e9-9d36-7b54a78fa71e.png)

**Comment by blavenie** [comment]
Fix in v0.17.4
