### ISSUE TITLE
Show header bar on individual measure modal ?

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#172]
Lorsque l'on est dans mesures individuelles, est ce possible de garder apparent le bandeau principale avec les informations sur la marée, l'op, etc., même si c'est une nouvelle fenêtre ?
![image](https://user-images.githubusercontent.com/45093466/76500491-e6bc3500-6440-11ea-8b5b-c0bb2f00e2ad.png)

Ce n'est pas le cas non plus pour les lots par espèce en mode tablette :+1: 
![image](https://user-images.githubusercontent.com/45093466/76501785-2c79fd00-6443-11ea-95b0-7700e6972d9e.png)

C'est pourtant le cas quand on est dans la partie lot par espèce en mode bureau :
![image](https://user-images.githubusercontent.com/45093466/76500600-1cf9b480-6441-11ea-8375-0333b6cd2f4e.png)

**Comment by blavenie** [comment]
Oui, c'est normal, c'ets une fenetre modale, qui prend toute la place pour des questions d'optimisation de place. Ce n'est pas le même fonctionnement qu'un écran édition. du coup, c'est pour cela que les couleur ne sont pas identique.
