### ISSUE TITLE
[Operation] New OPE : Auto fill species, from program/strategy

### ISSUE THREAD

**Issue by blavenie** [sumaris-net/sumaris-app#176]
When creating a new operation, species must be filled by applied strategy's taxon groups.

**Comment by blavenie** [comment]
> Les pêcheurs seraient intéressés pour que l’espèce cible soit remplie par défaut. 2 options :
>   - Soit via la dernière opération saisie.
>   - Sur la marée : créer un sous-programme (PSFM) pour figer la liste des espèces ; 
>Baudroie/Eglefin, Baudroie, Eglefin, Cabillaud, Cabillaud/Eglefin, Baudroie/Eglefin/Pocheteaux, Pocheteaux ;

**Comment by blavenie** [comment]
Reste à crééer : 
 - Le PSFM (id=28), avec les valeurs qualitatives (QV) associées;
 - les listes d'expèces en fonction de chaque valeur qualitative.

Idée d'implémentation : Utiliser le code de la valeur qualitative, pour déduire la liste d'espèce ?

**Comment by MarionLPDB** [comment]
Bjr Benoit,
- La liste est complète et correcte
- COD est déjà présent, c'est RJB qu'il faut créer
- Cette fonction de pré-remplissage doit aussi s'appliquer à la saisie bureau. Ce ne sera pas compliqué pour nous de revenir sur les marées déjà saisies pour le rajouter.
Merci
