### ISSUE TITLE
Vessel: slip registration code in 2 ?

### ISSUE THREAD

**Issue by blavenie** [sumaris-net/sumaris-app#18]
- L'observateur ne connait pas toujours l'immat internationnale du navire. Peut-être serait-il préférable, pour éviter de se retrouver avec des saisies uniquement d'immat nationaux, de prévoir de diviser l'immat en 2 champs : 
une 1ere partie incrémentée par défaut sur le début de l'immat définie par le code pays, selon le pays d'appartenance de la structure du saisisseur (exple : FR000, UK000, BE000, NL000...), puis une autre partie correspondant au numéro d'immat nationale que le saisisseur va entrer (exple : BL914059).
J'ai commencé à regarder les codes d'immatriculations internationaux, et ça ne semble pas si simple que ça. On peut rester sur du simple pour l'instant, mais à terme, si tu penses que ça peut servir, je pourrai me renseigner des bons référentiels de codifications pour identifier au niveau national les navires.

**Comment by hgaden** [comment]
A SUPPRIMER, je n'y arrive pas
