### ISSUE TITLE
Champs type d'auto-échantillonnage

### ISSUE THREAD

**Issue by thomasLPDB** [sumaris-net/sumaris-app#183]
-implémenter la liste avec a minima « pocheteau » + ceux qui font le pocheteau en plus d’une autre espèce (Baudroie/pocheteau + Eglefin/pocheteau)
-la configuration en début de marée n’est active que pour la baudroie pour le pré-affichage des espèces dans l’onglet capture

**Comment by blavenie** [comment]
cf ticket https://github.com/sumaris-net/sumaris-app/issues/176
