### ISSUE TITLE
Pocheteaux : manque le taux d'échantillonnage

### ISSUE THREAD

**Issue by thomasLPDB** [sumaris-net/sumaris-app#184]
-Prévoir le champ taux d'échantillonnage si mesure de pocheteau
-A ce stade le champ Partie débarqué n'est pas utile (l'espèce est interdite)

**Comment by blavenie** [comment]
je vais ajouté le taux d'échantillonnage.
En revanche, peut on laisser tout de même la partir débarquée ? Pour éviter un nouveau paramétrage spécifique à l'espèce ?

**Comment by blavenie** [comment]
Comme le nombre d'individu total est saisit, le taux d'échantillonnage peut etre calculé à partir du nombre d'individus mesurés

**Comment by blavenie** [comment]
Vérifier que le taux d'échantillonnage est bien calculé et stocké en BDD
