### ISSUE TITLE
Libellés en anglais à traduire

### ISSUE THREAD

**Issue by MarionLPDB** [sumaris-net/sumaris-app#189]
C'est notamment le cas dans les types d'engins, espèces cibles

**Comment by blavenie** [comment]
Traduction à réaliser via l'interface d'administration :
 - Engin : https://adap.pecheursdebretagne.eu/referential/list?entity=Gear
 - Expèce cibles : 
  * https://adap.pecheursdebretagne.eu/referential/list?entity=TaxonGroup
  * Filtrer sur "niveau = NATIONAL"
