### ISSUE TITLE
Sélection des listes déroulantes, en mode paysage (Ex: programme, espèces cible)

### ISSUE THREAD

**Issue by MarionLPDB** [sumaris-net/sumaris-app#190]
J'ai remarqué que lorsqu'on saisit deux OP à suivre, la sélection de l'espèce cible fonctionne pour la première mais pour la deuxième elle n'apparait plus dans liste ou plutôt elle apparait mais combinée à l'engin.

**Comment by blavenie** [comment]
Peux-tu préciser stp :
 - Si bug sur tablette
 - Si tu avais fait un synchro (Activer le mode hors-ligne) avant
 - Si tu as avais du réseau ou non
