### ISSUE TITLE
V:0.7.0 : Chrome : bloquant : message erreur saisie OP

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#27]
Message : Can't find field fishingStartDateTime on object { "id": 527, "startDateTime": "2018-11-02T06:00:00.000Z", "endDateTime": "2018-11-02T15:00:00.000Z", "phy

**Comment by hgaden** [comment]
je m'aperçois, après avoir fait Ctrl R, que toutes les OP tests ont été saisies (toutes celles que je croyais ne pas avoir été sauvegardées). Du coup, certaines OP sont enregistrées sans même avoir l'info sur le poids de la capture.
Tout ça concerne la marée 514 avec le navire TestChrome

**Comment by blavenie** [comment]
duplicate of #31
