### ISSUE TITLE
Trip: error while saving : "Cannot find field fishingStartDateTime"

### ISSUE THREAD

**Issue by gillesbernardSUMARiS** [sumaris-net/sumaris-app#31]
Impossible de saisir une marée cf pièce jointe par courriel

**Comment by blavenie** [comment]
![image](https://user-images.githubusercontent.com/5269556/49278415-01a1aa80-f485-11e8-98b0-ee6b5aa9c5e9.png)

**Comment by blavenie** [comment]
This is due to the apollo cache limitation, when calling `apollo.getCLient().readQuery()`
See https://github.com/apollographql/react-apollo/issues/1776#issuecomment-372237940

=> Need to add a try/catch to avoid application error
