### ISSUE TITLE
V0.8.2: haul : Error message BLOQUANT / Error communicating with the server

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#38]
impossible de saisir une nouvelle opération de pêche : 

'Error communicating with the server.
If the problem persists, please contact your administrator.'
![capture](https://user-images.githubusercontent.com/45093466/49547193-f06bfa00-f8d9-11e8-8dde-6a5d3af969cc.JPG)

**Comment by blavenie** [comment]
fixed in v0.9.1
