### ISSUE TITLE
V0.6.2 : Sur la forme

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#5]
- **Home page** : en français "Bienvenue sur le portail SUMARiS !" : ramener le "!" sur la même ligne que le texte.
- temps d'affichage des listes déroulantes parfois long
- pour optimiser le temps de saisie, quand la marée est sauvegarder, ça serait bien que d'office la page suivante à remplir s'ouvre, idem pour la suite.
- **Marée / engin** : dans l'idéale, voir tous les champs concernant une étape me semble important (ça donne une vue d'ensemble). Pour gagner de la place, est ce possible de mettre la valeur d'une information à côté et non en dessous ?
-

**Comment by blavenie** [comment]
- Home page : corrigé en 0.6.3
- temps liste déroulante : doit être long surtout lors des premières utilisations. J'ai activer un "cache" pour cela.
