### ISSUE TITLE
Sauvegarde 

### ISSUE THREAD

**Issue by gillesbernardSUMARiS** [sumaris-net/sumaris-app#61]
Bonjour,
Pour chaque sauvegarde des ops, une attente d'environ 10 secondes avant l'apparition du message d'erreur : Erreur de communication avec le serveur.
Si le problème persiste, veuillez contacter votre administrateur.

Il me faut ensuite cliquer une nouvelle fois sur sauvegarder afin de valider l'op.

Gilles

**Comment by hgaden** [comment]
Hgaden vu avec gilles. Erreur impossible à reproduire, car sauvegarde refonctionne après 2nd essai. A suivre
