### ISSUE TITLE
Sauvegarde des individus de suivie

### ISSUE THREAD

**Issue by gillesbernardSUMARiS** [sumaris-net/sumaris-app#63]
Bjr, 
Problème de sauvegarde à la fin de la saisie de l'ensemble des individus dans l'onglet de suivi. 
Il me faut par prudence sauvegarder à chaque ligne plutôt que d'attendre d'en faire plusieurs pour ne pas perdre toutes les données remplis.
Problème, il arrive fréquemment qu'il ne soit plus possible d'ajouter une ligne, il me faut alors fermer, revenir sur l'op pour y retourner et pouvoir ajouter une ligne, et des lignes n'ont pu être sauvegarder à ce moment et sont à ressaisir

**Comment by hgaden** [comment]
En insistant, Gille à réussi à tout saisir. ça semble aléatoire... Je lui ai demandé si il cliquait bien sur le V de chaque ligne avant d'en ajouter une 2nd. Et oui, donc problème à suivre si se reproduit.

**Comment by blavenie** [comment]
should be fixed in v0.9.3
