### ISSUE TITLE
Mesures individuelles / Total length : obligatoire ou facultatif

### ISSUE THREAD

**Issue by hgaden** [sumaris-net/sumaris-app#65]
Il arrive qu'un observateur oublie de mesurer un individus. Pour autant, l'information sur le sexe, l'espèce est importante. Le champs étant obligatoire, il ne peut pas le saisir (c'est arrivé à Gilles). La mesure peut-elle être facultative et si rien n'est saisi, par sécurité pour s'assurer que ce n'est pas une erreur, un message pourrait-il s'afficher pour indiquer : "vous avez oubliez de saisir une longueur individuelle. Si c'est une erreur, complétez, sinon sauvegardez". Un truc dans le genre...

**Comment by gillesbernardSUMARiS** [comment]
Pour le sexe nous avons le choix entre M et F et UNK, UNK étant évidemment un oubli.
Pour la mesure l'oubli est possible également, je pense qu'il faut annulé le paramètre obligatoire.
Par défaut j'ai indiqué "0" cm. Le chiffre zéro étant un chiffre qui disparaît à chaque saisie (poids, cloud cover etc), 
Une fois le chiffre zéro "accepté" par la data base, une raie non mesurée (oubli ou mauvaise lecture lors du remplissage des formulaires) ne me permettra pas de remplir la ligne pour un individu testé en "S" pour une OP
